language: python
sudo: required
dist: precise

os:
  - linux
#  - osx

compiler:
  - gcc
  - clang

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_install: 
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    brew update;
    brew install mono;
    brew install pyenv;
    pyenv install $PYTHON;
    fi
  - echo "Installing CUDA"
  - wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1204/x86_64/cuda-repo-ubuntu1204_7.0-28_amd64.deb
  - sudo dpkg -i cuda-repo-ubuntu1204_7.0-28_amd64.deb
  - cd ${TRAVIS_BUILD_DIR}
  - sudo apt-get update
  - sudo apt-get install cuda-drivers cuda-core-7-0 cuda-cudart-dev-7-0
  - echo "Creating symbolic link to OpenCL because 12.04 CUDA doesn't do it."
  - sudo ln -s /usr/local/cuda-7.0/lib64/libOpenCL.so /usr/lib/x86_64-linux-gnu/libOpenCL.so
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libgfortran.so.3 /usr/lib/libgfortran.so

install:
  - pip install .

script:
  - python test/test.py
