#language: generic
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

os:
  - linux
#  - osx

compiler:
  - gcc
#  - clang

# Perform the manual steps on osx to install python3 and activate venv
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python3; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi


install:
#  - sudo apt-get update
#
#  # Deal with python versions and osx vs linux
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
#      export MYSYS="MacOSX";
#    else
#      export MYSYS="Linux";
#    fi
#  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
#      wget https://repo.continuum.io/miniconda/Miniconda2-latest-$MYSYS-x86_64.sh -O miniconda.sh;
#    else
#      wget https://repo.continuum.io/miniconda/Miniconda3-latest-$MYSYS-x86_64.sh -O miniconda.sh;
#    fi
#
#  # Get what we need from conda
#  - bash miniconda.sh -b -p $HOME/miniconda
#  - export PATH="$HOME/miniconda/bin:$PATH"
#  - hash -r
#  - conda config --set always_yes yes --set changeps1 no
#  - conda update -q conda
#  - conda info -a
#  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
#  - source activate test-environment
#
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
#      export MYSYS="MacOSX";
#    else
#      export MYSYS="Linux";
#    fi


  - python setup.py install

script:
  - python test/test.py
