env:
  global:
    - TWINE_USERNAME=dhidas

os: linux
language: python
python: 3.6

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - os: osx
      language: generic
      env: PYVER=3.6
    - os: osx
      language: generic
      env: PYVER=3.5

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pyenv ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv versions ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv install $PYVER ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv local $PYVER ; fi


install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install -U twine ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull $DOCKER_IMAGE ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python setup.py install ; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install -U twine ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/.ci/build-wheels.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python test/test/py ; fi
  - ls wheelhouse/
  #- twine upload -r pypi wheelhouse/*manylinux1_x86_64.whl

