env:
  global:
    - TWINE_USERNAME=dhidas

os: linux
language: python
python: 3.6

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - os: osx
      language: generic
      env: PYVER=3.6

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python$PYVER ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python$PYVER ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate ; fi


install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install -U twine ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull $DOCKER_IMAGE ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python setup.py install ; fi

script:
  - pip install -U twine
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/.ci/build-wheels.sh
  - ls wheelhouse/
  #- twine upload -r pypi wheelhouse/*manylinux1_x86_64.whl

