language: python
sudo: false
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_install: 
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    brew update;
    brew install pyenv;
    pyenv install $PYTHON;
    fi

install:
  - pip install .

script:
  - python test/test.py
