language: python
#sudo: false
#dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_install: 
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh  -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
    - source activate test-environment
    fi

install:
  - pip install .

script:
  - python test/test.py
