name: oscars
channels:
- conda-forge
- defaults
dependencies:
  - python=3.5*
  - matplotlib
  - jupyter
  - gcc
  - mpi4py
  - sphinx
  - pip:
    - recommonmark
    - sphinx_rtd_theme
    - numpydoc
