name: oscars
channels:
- conda-forge
- defaults
dependencies:
  - python=3.6*
  - matplotlib
  - jupyter
  - scipy
  - numpy
  - gcc
  - mpi4py
  - sphinx
  - pip:
    - recommonmark
    - sphinx_rtd_theme
    - numpydoc
